# Generated by Django 3.2 on 2021-04-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input1', models.CharField(max_length=100)),
                ('input2', models.CharField(max_length=100)),
                ('input3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StlModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=30)),
            ],
        ),
    ]
