# Generated by Django 3.2 on 2021-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stl_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stlmodels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
