# Generated by Django 3.2.2 on 2021-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stl_upload', '0002_alter_stlmodels_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProcess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('center_x', models.IntegerField()),
                ('center_y', models.IntegerField()),
                ('center_z', models.IntegerField()),
                ('orientation_x', models.FloatField()),
                ('orientation_y', models.FloatField()),
                ('orientation_z', models.FloatField()),
                ('opacity', models.FloatField()),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
    ]
