# Generated by Django 3.1 on 2021-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stl_upload', '0002_auto_20210519_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstl',
            name='file',
            field=models.FileField(default='settings.STATIC_URL/uploads/user_uploaded_model.stl', upload_to='uploads'),
        ),
    ]
