# Generated by Django 3.2.2 on 2021-05-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stl_upload', '0003_userprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprocess',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
